# Generated by Django 3.1.2 on 2020-11-19 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tiny', '0002_auto_20201111_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinynote',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tinynote',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('6b75853c-7e9b-48ea-b699-8ed62e43e761')),
        ),
    ]
