# Generated by Django 3.1.2 on 2020-10-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuillNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.EmailField(default='admin@quill-notes.com', max_length=254)),
                ('title', models.CharField(max_length=500)),
                ('quill_delta', models.TextField(blank=True, default='')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('note_id', models.UUIDField()),
            ],
        ),
    ]
