# Generated by Django 3.1.2 on 2020-10-27 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('editorjs', '0002_auto_20201027_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editornote',
            old_name='blocks',
            new_name='raw_data',
        ),
        migrations.AlterField(
            model_name='editornote',
            name='note_id',
            field=models.UUIDField(default=uuid.UUID('1de44f97-4039-4655-8678-282a362bc88d')),
        ),
    ]
