# Generated by Django 3.1.2 on 2020-11-11 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('editorjs', '0005_auto_20201111_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editornote',
            name='note_id',
            field=models.UUIDField(default=uuid.UUID('2f1a5ff3-5be3-4db7-bf9a-9ea01bd3d6a9')),
        ),
    ]
