# Generated by Django 3.1.2 on 2020-11-19 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('editorjs', '0006_auto_20201111_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editornote',
            name='note_id',
            field=models.UUIDField(default=uuid.UUID('dd37deaf-10a8-445a-b634-cadd7f51c19d')),
        ),
    ]
